// Exportação centralizada dos componentes UI
export { Button } from './button'
export { Input } from './input'
export { default as Modal, ConfirmModal } from './Modal'
export { Card, CardHeader, CardContent, CardFooter, CardTitle, CardDescription } from './card'
export { Badge } from './badge'
export { default as Icon, DashboardIcon } from './Icon'

// Re-exportar outros componentes shadcn
export { Label } from './label'
export { Textarea } from './textarea'
export { Switch } from './switch'
export { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from './select'
export { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from './dialog'
export { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from './dropdown-menu'
export { Tabs, TabsContent, TabsList, TabsTrigger } from './tabs'
export { Progress } from './progress'
export { Skeleton } from './skeleton'
export { ScrollArea } from './scroll-area'
export { Breadcrumb, BreadcrumbItem, BreadcrumbLink, BreadcrumbList, BreadcrumbPage, BreadcrumbSeparator } from './breadcrumb'
export { Avatar, AvatarImage, AvatarFallback } from './avatar'
export { Alert, AlertDescription, AlertTitle } from './alert'
export { Sheet, SheetContent, SheetDescription, SheetFooter, SheetHeader, SheetTitle, SheetTrigger } from './sheet'
export { Separator } from './separator'
export { RadioGroup, RadioGroupItem } from './radio-group'
export { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from './tooltip'
export { Toaster } from './sonner'